Temp changes

diff --git a/.github/workflows/pulsar-ci.yaml b/.github/workflows/pulsar-ci.yaml
--- a/.github/workflows/pulsar-ci.yaml
+++ b/.github/workflows/pulsar-ci.yaml
@@ -219,245 +219,245 @@ jobs:
           action: wait
 
 
-  unit-tests:
-    name: CI - Unit - ${{ matrix.name }}
-    env:
-      JOB_NAME: CI - Unit - ${{ matrix.name }}
-      COLLECT_COVERAGE: "${{ needs.preconditions.outputs.collect_coverage }}"
-      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
-      CI_JDK_MAJOR_VERSION: ${{ needs.preconditions.outputs.jdk_major_version }}
-      TRACE_TEST_RESOURCE_CLEANUP: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trace_test_resource_cleanup || 'off' }}
-      TRACE_TEST_RESOURCE_CLEANUP_DIR: ${{ github.workspace }}/target/trace-test-resource-cleanup
-      THREAD_LEAK_DETECTOR_WAIT_MILLIS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.thread_leak_detector_wait_millis || 10000 }}
-      THREAD_LEAK_DETECTOR_DIR: ${{ github.workspace }}/target/thread-leak-dumps
-    runs-on: ubuntu-22.04
-    timeout-minutes: ${{ matrix.timeout || 60 }}
-    needs: ['preconditions', 'build-and-license-check']
-    if: ${{ needs.preconditions.outputs.docs_only != 'true' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: Other
-            group: OTHER
-            timeout: 75
-          - name: Brokers - Broker Group 1
-            group: BROKER_GROUP_1
-          - name: Brokers - Broker Group 2
-            group: BROKER_GROUP_2
-          - name: Brokers - Broker Group 3
-            group: BROKER_GROUP_3
-          - name: Brokers - Broker Group 4
-            group: BROKER_GROUP_4
-          - name: Brokers - Client Api
-            group: BROKER_CLIENT_API
-          - name: Brokers - Client Impl
-            group: BROKER_CLIENT_IMPL
-          - name: Proxy
-            group: PROXY
-          - name: Pulsar IO
-            group: PULSAR_IO
-            timeout: 75
-          - name: Pulsar IO - Elastic Search
-            group: PULSAR_IO_ELASTIC
-          - name: Pulsar IO - Kafka Connect Adaptor
-            group: PULSAR_IO_KAFKA_CONNECT
-          - name: Pulsar Client
-            group: CLIENT
-          - name: Pulsar Metadata
-            group: METADATA
-
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
-
-      - name: Tune Runner VM
-        uses: ./.github/actions/tune-runner-vm
-
-      - name: Clean Disk when tracing test resource cleanup
-        if: ${{ env.TRACE_TEST_RESOURCE_CLEANUP != 'off' }}
-        uses: ./.github/actions/clean-disk
-
-      - name: Setup ssh access to build runner VM
-        # ssh access is enabled for builds in own forks
-        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        uses: ./.github/actions/ssh-access
-        continue-on-error: true
-        with:
-          limit-access-to-actor: true
-
-      - name: Cache Maven dependencies
-        uses: actions/cache@v4
-        timeout-minutes: 5
-        with:
-          path: |
-            ~/.m2/repository/*/*/*
-            !~/.m2/repository/org/apache/pulsar
-          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-m2-dependencies-core-modules-
-
-      - name: Set up JDK ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
-        uses: actions/setup-java@v4
-        with:
-          distribution: ${{ env.JDK_DISTRIBUTION }}
-          java-version: ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
-
-      - name: Install gh-actions-artifact-client.js
-        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
-
-      - name: Restore maven build results from Github artifact cache
-        run: |
-          cd $HOME
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh snapshot_pulsar_maven_artifacts
-
-      - name: Run setup commands
-        run: |
-          ${{ matrix.setup }}
-
-      - name: Run unit test group '${{ matrix.group }}'
-        run: |
-          CHANGED_TESTS="${{ needs.preconditions.outputs.tests_files }}" ./build/run_unit_group.sh ${{ matrix.group }}
-
-      - name: Upload coverage to build artifacts
-        if: ${{ needs.preconditions.outputs.collect_coverage == 'true' }}
-        run: $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh upload_unittest_coverage_files ${{ matrix.group }}
-
-      - name: print JVM thread dumps when cancelled
-        if: cancelled()
-        run: $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh print_thread_dumps
-
-      - name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
-        if: ${{ always() }}
-        uses: ./.github/actions/copy-test-reports
-
-      - name: Publish Test Report
-        uses: apache/pulsar-test-infra/action-junit-report@master
-        if: ${{ always() }}
-        with:
-          report_paths: 'test-reports/TEST-*.xml'
-          annotate_only: 'true'
-
-      - name: Report detected thread leaks
-        if: ${{ always() }}
-        run: |
-          if [ -d "$THREAD_LEAK_DETECTOR_DIR" ]; then
-            cd "$THREAD_LEAK_DETECTOR_DIR"
-            cat threadleak*.txt | awk '/^Summary:/ {print "::warning::" $0 "\n"; next} {print}'
-          fi
-
-      - name: Upload Surefire reports
-        uses: actions/upload-artifact@v4
-        if: ${{ !success() || env.TRACE_TEST_RESOURCE_CLEANUP != 'off' }}
-        with:
-          name: Unit-${{ matrix.group }}-surefire-reports
-          path: surefire-reports
-          retention-days: 7
-
-      - name: Upload possible heap dump, core dump or crash files
-        uses: actions/upload-artifact@v4
-        if: ${{ always() }}
-        with:
-          name: Unit-${{ matrix.group }}-dumps
-          path: |
-            /tmp/*.hprof
-            **/hs_err_*.log
-            **/core.*
-            ${{ env.TRACE_TEST_RESOURCE_CLEANUP_DIR }}/*
-            ${{ env.THREAD_LEAK_DETECTOR_DIR }}/*
-          retention-days: 7
-          if-no-files-found: ignore
-
-      - name: Wait for ssh connection when build fails
-        # ssh access is enabled for builds in own forks
-        uses: ./.github/actions/ssh-access
-        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        continue-on-error: true
-        with:
-          action: wait
-
-
-  unit-tests-upload-coverage:
-    name: CI - Unit - Upload Coverage
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    needs: ['preconditions', 'unit-tests']
-    env:
-      CI_JDK_MAJOR_VERSION: ${{ needs.preconditions.outputs.jdk_major_version }}
-    if: ${{ needs.preconditions.outputs.collect_coverage == 'true' }}
-
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
-
-      - name: Tune Runner VM
-        uses: ./.github/actions/tune-runner-vm
-
-      - name: Setup ssh access to build runner VM
-        # ssh access is enabled for builds in own forks
-        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        uses: ./.github/actions/ssh-access
-        continue-on-error: true
-        with:
-          limit-access-to-actor: true
-
-      - name: Cache Maven dependencies
-        uses: actions/cache@v4
-        timeout-minutes: 5
-        with:
-          path: |
-            ~/.m2/repository/*/*/*
-            !~/.m2/repository/org/apache/pulsar
-          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-m2-dependencies-core-modules-
-
-      - name: Set up JDK ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
-        uses: actions/setup-java@v4
-        with:
-          distribution: ${{ env.JDK_DISTRIBUTION }}
-          java-version: ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
-
-      - name: Install gh-actions-artifact-client.js
-        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
-
-      - name: Restore maven build results from Github artifact cache
-        run: |
-          cd $HOME
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh snapshot_pulsar_maven_artifacts
-
-      - name: Restore coverage files from build artifacts and create Jacoco reports
-        run: |
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_unittest_coverage_files
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh create_test_coverage_report 
-          cd $GITHUB_WORKSPACE/target
-          zip -qr jacoco_test_coverage_report_unittests.zip jacoco_test_coverage_report || true
-
-      - name: Upload Jacoco report files to build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: Jacoco-coverage-report-unittests
-          path: target/jacoco_test_coverage_report_unittests.zip
-          retention-days: 3
-
-      - name: Upload to Codecov
-        uses: ./.github/actions/upload-coverage
-        with:
-          flags: unittests
-
-      - name: Delete coverage files from build artifacts
-        run: |
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh delete_unittest_coverage_files
-
-      - name: Wait for ssh connection when build fails
-        # ssh access is enabled for builds in own forks
-        uses: ./.github/actions/ssh-access
-        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        continue-on-error: true
-        with:
-          action: wait
+#  unit-tests:
+#    name: CI - Unit - ${{ matrix.name }}
+#    env:
+#      JOB_NAME: CI - Unit - ${{ matrix.name }}
+#      COLLECT_COVERAGE: "${{ needs.preconditions.outputs.collect_coverage }}"
+#      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
+#      CI_JDK_MAJOR_VERSION: ${{ needs.preconditions.outputs.jdk_major_version }}
+#      TRACE_TEST_RESOURCE_CLEANUP: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trace_test_resource_cleanup || 'off' }}
+#      TRACE_TEST_RESOURCE_CLEANUP_DIR: ${{ github.workspace }}/target/trace-test-resource-cleanup
+#      THREAD_LEAK_DETECTOR_WAIT_MILLIS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.thread_leak_detector_wait_millis || 10000 }}
+#      THREAD_LEAK_DETECTOR_DIR: ${{ github.workspace }}/target/thread-leak-dumps
+#    runs-on: ubuntu-22.04
+#    timeout-minutes: ${{ matrix.timeout || 60 }}
+#    needs: ['preconditions', 'build-and-license-check']
+#    if: ${{ needs.preconditions.outputs.docs_only != 'true' }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - name: Other
+#            group: OTHER
+#            timeout: 75
+#          - name: Brokers - Broker Group 1
+#            group: BROKER_GROUP_1
+#          - name: Brokers - Broker Group 2
+#            group: BROKER_GROUP_2
+#          - name: Brokers - Broker Group 3
+#            group: BROKER_GROUP_3
+#          - name: Brokers - Broker Group 4
+#            group: BROKER_GROUP_4
+#          - name: Brokers - Client Api
+#            group: BROKER_CLIENT_API
+#          - name: Brokers - Client Impl
+#            group: BROKER_CLIENT_IMPL
+#          - name: Proxy
+#            group: PROXY
+#          - name: Pulsar IO
+#            group: PULSAR_IO
+#            timeout: 75
+#          - name: Pulsar IO - Elastic Search
+#            group: PULSAR_IO_ELASTIC
+#          - name: Pulsar IO - Kafka Connect Adaptor
+#            group: PULSAR_IO_KAFKA_CONNECT
+#          - name: Pulsar Client
+#            group: CLIENT
+#          - name: Pulsar Metadata
+#            group: METADATA
+#
+#    steps:
+#      - name: checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Tune Runner VM
+#        uses: ./.github/actions/tune-runner-vm
+#
+#      - name: Clean Disk when tracing test resource cleanup
+#        if: ${{ env.TRACE_TEST_RESOURCE_CLEANUP != 'off' }}
+#        uses: ./.github/actions/clean-disk
+#
+#      - name: Setup ssh access to build runner VM
+#        # ssh access is enabled for builds in own forks
+#        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        uses: ./.github/actions/ssh-access
+#        continue-on-error: true
+#        with:
+#          limit-access-to-actor: true
+#
+#      - name: Cache Maven dependencies
+#        uses: actions/cache@v4
+#        timeout-minutes: 5
+#        with:
+#          path: |
+#            ~/.m2/repository/*/*/*
+#            !~/.m2/repository/org/apache/pulsar
+#          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-m2-dependencies-core-modules-
+#
+#      - name: Set up JDK ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: ${{ env.JDK_DISTRIBUTION }}
+#          java-version: ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
+#
+#      - name: Install gh-actions-artifact-client.js
+#        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
+#
+#      - name: Restore maven build results from Github artifact cache
+#        run: |
+#          cd $HOME
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh snapshot_pulsar_maven_artifacts
+#
+#      - name: Run setup commands
+#        run: |
+#          ${{ matrix.setup }}
+#
+#      - name: Run unit test group '${{ matrix.group }}'
+#        run: |
+#          CHANGED_TESTS="${{ needs.preconditions.outputs.tests_files }}" ./build/run_unit_group.sh ${{ matrix.group }}
+#
+#      - name: Upload coverage to build artifacts
+#        if: ${{ needs.preconditions.outputs.collect_coverage == 'true' }}
+#        run: $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh upload_unittest_coverage_files ${{ matrix.group }}
+#
+#      - name: print JVM thread dumps when cancelled
+#        if: cancelled()
+#        run: $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh print_thread_dumps
+#
+#      - name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
+#        if: ${{ always() }}
+#        uses: ./.github/actions/copy-test-reports
+#
+#      - name: Publish Test Report
+#        uses: apache/pulsar-test-infra/action-junit-report@master
+#        if: ${{ always() }}
+#        with:
+#          report_paths: 'test-reports/TEST-*.xml'
+#          annotate_only: 'true'
+#
+#      - name: Report detected thread leaks
+#        if: ${{ always() }}
+#        run: |
+#          if [ -d "$THREAD_LEAK_DETECTOR_DIR" ]; then
+#            cd "$THREAD_LEAK_DETECTOR_DIR"
+#            cat threadleak*.txt | awk '/^Summary:/ {print "::warning::" $0 "\n"; next} {print}'
+#          fi
+#
+#      - name: Upload Surefire reports
+#        uses: actions/upload-artifact@v4
+#        if: ${{ !success() || env.TRACE_TEST_RESOURCE_CLEANUP != 'off' }}
+#        with:
+#          name: Unit-${{ matrix.group }}-surefire-reports
+#          path: surefire-reports
+#          retention-days: 7
+#
+#      - name: Upload possible heap dump, core dump or crash files
+#        uses: actions/upload-artifact@v4
+#        if: ${{ always() }}
+#        with:
+#          name: Unit-${{ matrix.group }}-dumps
+#          path: |
+#            /tmp/*.hprof
+#            **/hs_err_*.log
+#            **/core.*
+#            ${{ env.TRACE_TEST_RESOURCE_CLEANUP_DIR }}/*
+#            ${{ env.THREAD_LEAK_DETECTOR_DIR }}/*
+#          retention-days: 7
+#          if-no-files-found: ignore
+#
+#      - name: Wait for ssh connection when build fails
+#        # ssh access is enabled for builds in own forks
+#        uses: ./.github/actions/ssh-access
+#        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        continue-on-error: true
+#        with:
+#          action: wait
+#
+#
+#  unit-tests-upload-coverage:
+#    name: CI - Unit - Upload Coverage
+#    runs-on: ubuntu-22.04
+#    timeout-minutes: 30
+#    needs: ['preconditions', 'unit-tests']
+#    env:
+#      CI_JDK_MAJOR_VERSION: ${{ needs.preconditions.outputs.jdk_major_version }}
+#    if: ${{ needs.preconditions.outputs.collect_coverage == 'true' }}
+#
+#    steps:
+#      - name: checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Tune Runner VM
+#        uses: ./.github/actions/tune-runner-vm
+#
+#      - name: Setup ssh access to build runner VM
+#        # ssh access is enabled for builds in own forks
+#        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        uses: ./.github/actions/ssh-access
+#        continue-on-error: true
+#        with:
+#          limit-access-to-actor: true
+#
+#      - name: Cache Maven dependencies
+#        uses: actions/cache@v4
+#        timeout-minutes: 5
+#        with:
+#          path: |
+#            ~/.m2/repository/*/*/*
+#            !~/.m2/repository/org/apache/pulsar
+#          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-m2-dependencies-core-modules-
+#
+#      - name: Set up JDK ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: ${{ env.JDK_DISTRIBUTION }}
+#          java-version: ${{ matrix.jdk || env.CI_JDK_MAJOR_VERSION }}
+#
+#      - name: Install gh-actions-artifact-client.js
+#        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
+#
+#      - name: Restore maven build results from Github artifact cache
+#        run: |
+#          cd $HOME
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh snapshot_pulsar_maven_artifacts
+#
+#      - name: Restore coverage files from build artifacts and create Jacoco reports
+#        run: |
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_unittest_coverage_files
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh create_test_coverage_report
+#          cd $GITHUB_WORKSPACE/target
+#          zip -qr jacoco_test_coverage_report_unittests.zip jacoco_test_coverage_report || true
+#
+#      - name: Upload Jacoco report files to build artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: Jacoco-coverage-report-unittests
+#          path: target/jacoco_test_coverage_report_unittests.zip
+#          retention-days: 3
+#
+#      - name: Upload to Codecov
+#        uses: ./.github/actions/upload-coverage
+#        with:
+#          flags: unittests
+#
+#      - name: Delete coverage files from build artifacts
+#        run: |
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh delete_unittest_coverage_files
+#
+#      - name: Wait for ssh connection when build fails
+#        # ssh access is enabled for builds in own forks
+#        uses: ./.github/actions/ssh-access
+#        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        continue-on-error: true
+#        with:
+#          action: wait
 
   pulsar-java-test-image:
     name: Build Pulsar java-test-image docker image
